name: mutli_service_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.1.0
  shared_preferences: ^2.0.12
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10




  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true


